// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/merchantuserbankaccount"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/predicate"
)

// MerchantUserBankAccountDelete is the builder for deleting a MerchantUserBankAccount entity.
type MerchantUserBankAccountDelete struct {
	config
	hooks    []Hook
	mutation *MerchantUserBankAccountMutation
}

// Where appends a list predicates to the MerchantUserBankAccountDelete builder.
func (mubad *MerchantUserBankAccountDelete) Where(ps ...predicate.MerchantUserBankAccount) *MerchantUserBankAccountDelete {
	mubad.mutation.Where(ps...)
	return mubad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mubad *MerchantUserBankAccountDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mubad.hooks) == 0 {
		affected, err = mubad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MerchantUserBankAccountMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mubad.mutation = mutation
			affected, err = mubad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mubad.hooks) - 1; i >= 0; i-- {
			if mubad.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mubad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mubad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mubad *MerchantUserBankAccountDelete) ExecX(ctx context.Context) int {
	n, err := mubad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mubad *MerchantUserBankAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: merchantuserbankaccount.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: merchantuserbankaccount.FieldID,
			},
		},
	}
	if ps := mubad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mubad.driver, _spec)
}

// MerchantUserBankAccountDeleteOne is the builder for deleting a single MerchantUserBankAccount entity.
type MerchantUserBankAccountDeleteOne struct {
	mubad *MerchantUserBankAccountDelete
}

// Exec executes the deletion query.
func (mubado *MerchantUserBankAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := mubado.mubad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{merchantuserbankaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mubado *MerchantUserBankAccountDeleteOne) ExecX(ctx context.Context) {
	mubado.mubad.ExecX(ctx)
}
