// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/paymentcryptodetail"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/predicate"
)

// PaymentCryptoDetailDelete is the builder for deleting a PaymentCryptoDetail entity.
type PaymentCryptoDetailDelete struct {
	config
	hooks    []Hook
	mutation *PaymentCryptoDetailMutation
}

// Where appends a list predicates to the PaymentCryptoDetailDelete builder.
func (pcdd *PaymentCryptoDetailDelete) Where(ps ...predicate.PaymentCryptoDetail) *PaymentCryptoDetailDelete {
	pcdd.mutation.Where(ps...)
	return pcdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pcdd *PaymentCryptoDetailDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pcdd.hooks) == 0 {
		affected, err = pcdd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PaymentCryptoDetailMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pcdd.mutation = mutation
			affected, err = pcdd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pcdd.hooks) - 1; i >= 0; i-- {
			if pcdd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pcdd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pcdd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcdd *PaymentCryptoDetailDelete) ExecX(ctx context.Context) int {
	n, err := pcdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pcdd *PaymentCryptoDetailDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: paymentcryptodetail.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: paymentcryptodetail.FieldID,
			},
		},
	}
	if ps := pcdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pcdd.driver, _spec)
}

// PaymentCryptoDetailDeleteOne is the builder for deleting a single PaymentCryptoDetail entity.
type PaymentCryptoDetailDeleteOne struct {
	pcdd *PaymentCryptoDetailDelete
}

// Exec executes the deletion query.
func (pcddo *PaymentCryptoDetailDeleteOne) Exec(ctx context.Context) error {
	n, err := pcddo.pcdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentcryptodetail.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pcddo *PaymentCryptoDetailDeleteOne) ExecX(ctx context.Context) {
	pcddo.pcdd.ExecX(ctx)
}
