// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/cryptowallet"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/merchantuserbankaccount"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/payment"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/paymentbankingdetail"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/paymentcryptodetail"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/paymentewalletdetail"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/paymenttelcodetail"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/revision"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/setting"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/systembankaccount"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/systemcryptohotwallet"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/systemewallet"
	"gitlab.com/mcuc/monorepo/backend/stark/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cryptowalletFields := schema.CryptoWallet{}.Fields()
	_ = cryptowalletFields
	// cryptowalletDescCreatedAt is the schema descriptor for created_at field.
	cryptowalletDescCreatedAt := cryptowalletFields[1].Descriptor()
	// cryptowallet.DefaultCreatedAt holds the default value on creation for the created_at field.
	cryptowallet.DefaultCreatedAt = cryptowalletDescCreatedAt.Default.(func() time.Time)
	// cryptowalletDescUpdatedAt is the schema descriptor for updated_at field.
	cryptowalletDescUpdatedAt := cryptowalletFields[2].Descriptor()
	// cryptowallet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cryptowallet.DefaultUpdatedAt = cryptowalletDescUpdatedAt.Default.(func() time.Time)
	// cryptowallet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cryptowallet.UpdateDefaultUpdatedAt = cryptowalletDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cryptowalletDescCreatedBy is the schema descriptor for created_by field.
	cryptowalletDescCreatedBy := cryptowalletFields[3].Descriptor()
	// cryptowallet.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	cryptowallet.CreatedByValidator = cryptowalletDescCreatedBy.Validators[0].(func(string) error)
	// cryptowalletDescUpdatedBy is the schema descriptor for updated_by field.
	cryptowalletDescUpdatedBy := cryptowalletFields[4].Descriptor()
	// cryptowallet.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	cryptowallet.UpdatedByValidator = cryptowalletDescUpdatedBy.Validators[0].(func(string) error)
	// cryptowalletDescMerchantID is the schema descriptor for merchant_id field.
	cryptowalletDescMerchantID := cryptowalletFields[5].Descriptor()
	// cryptowallet.DefaultMerchantID holds the default value on creation for the merchant_id field.
	cryptowallet.DefaultMerchantID = cryptowalletDescMerchantID.Default.(int64)
	// cryptowallet.MerchantIDValidator is a validator for the "merchant_id" field. It is called by the builders before save.
	cryptowallet.MerchantIDValidator = cryptowalletDescMerchantID.Validators[0].(func(int64) error)
	// cryptowalletDescMerchantUserID is the schema descriptor for merchant_user_id field.
	cryptowalletDescMerchantUserID := cryptowalletFields[6].Descriptor()
	// cryptowallet.DefaultMerchantUserID holds the default value on creation for the merchant_user_id field.
	cryptowallet.DefaultMerchantUserID = cryptowalletDescMerchantUserID.Default.(int64)
	// cryptowallet.MerchantUserIDValidator is a validator for the "merchant_user_id" field. It is called by the builders before save.
	cryptowallet.MerchantUserIDValidator = cryptowalletDescMerchantUserID.Validators[0].(func(int64) error)
	// cryptowalletDescCryptoType is the schema descriptor for crypto_type field.
	cryptowalletDescCryptoType := cryptowalletFields[7].Descriptor()
	// cryptowallet.DefaultCryptoType holds the default value on creation for the crypto_type field.
	cryptowallet.DefaultCryptoType = cryptowalletDescCryptoType.Default.(int32)
	// cryptowallet.CryptoTypeValidator is a validator for the "crypto_type" field. It is called by the builders before save.
	cryptowallet.CryptoTypeValidator = cryptowalletDescCryptoType.Validators[0].(func(int32) error)
	// cryptowalletDescCryptoNetworkType is the schema descriptor for crypto_network_type field.
	cryptowalletDescCryptoNetworkType := cryptowalletFields[8].Descriptor()
	// cryptowallet.DefaultCryptoNetworkType holds the default value on creation for the crypto_network_type field.
	cryptowallet.DefaultCryptoNetworkType = cryptowalletDescCryptoNetworkType.Default.(int32)
	// cryptowallet.CryptoNetworkTypeValidator is a validator for the "crypto_network_type" field. It is called by the builders before save.
	cryptowallet.CryptoNetworkTypeValidator = cryptowalletDescCryptoNetworkType.Validators[0].(func(int32) error)
	// cryptowalletDescAddress is the schema descriptor for address field.
	cryptowalletDescAddress := cryptowalletFields[9].Descriptor()
	// cryptowallet.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	cryptowallet.AddressValidator = cryptowalletDescAddress.Validators[0].(func(string) error)
	// cryptowalletDescStatus is the schema descriptor for status field.
	cryptowalletDescStatus := cryptowalletFields[10].Descriptor()
	// cryptowallet.DefaultStatus holds the default value on creation for the status field.
	cryptowallet.DefaultStatus = cryptowalletDescStatus.Default.(int32)
	// cryptowallet.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	cryptowallet.StatusValidator = cryptowalletDescStatus.Validators[0].(func(int32) error)
	merchantuserbankaccountFields := schema.MerchantUserBankAccount{}.Fields()
	_ = merchantuserbankaccountFields
	// merchantuserbankaccountDescCreatedAt is the schema descriptor for created_at field.
	merchantuserbankaccountDescCreatedAt := merchantuserbankaccountFields[1].Descriptor()
	// merchantuserbankaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	merchantuserbankaccount.DefaultCreatedAt = merchantuserbankaccountDescCreatedAt.Default.(func() time.Time)
	// merchantuserbankaccountDescUpdatedAt is the schema descriptor for updated_at field.
	merchantuserbankaccountDescUpdatedAt := merchantuserbankaccountFields[2].Descriptor()
	// merchantuserbankaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	merchantuserbankaccount.DefaultUpdatedAt = merchantuserbankaccountDescUpdatedAt.Default.(func() time.Time)
	// merchantuserbankaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	merchantuserbankaccount.UpdateDefaultUpdatedAt = merchantuserbankaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// merchantuserbankaccountDescCreatedBy is the schema descriptor for created_by field.
	merchantuserbankaccountDescCreatedBy := merchantuserbankaccountFields[3].Descriptor()
	// merchantuserbankaccount.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	merchantuserbankaccount.CreatedByValidator = merchantuserbankaccountDescCreatedBy.Validators[0].(func(string) error)
	// merchantuserbankaccountDescUpdatedBy is the schema descriptor for updated_by field.
	merchantuserbankaccountDescUpdatedBy := merchantuserbankaccountFields[4].Descriptor()
	// merchantuserbankaccount.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	merchantuserbankaccount.UpdatedByValidator = merchantuserbankaccountDescUpdatedBy.Validators[0].(func(string) error)
	// merchantuserbankaccountDescBankName is the schema descriptor for bank_name field.
	merchantuserbankaccountDescBankName := merchantuserbankaccountFields[5].Descriptor()
	// merchantuserbankaccount.DefaultBankName holds the default value on creation for the bank_name field.
	merchantuserbankaccount.DefaultBankName = merchantuserbankaccountDescBankName.Default.(int32)
	// merchantuserbankaccount.BankNameValidator is a validator for the "bank_name" field. It is called by the builders before save.
	merchantuserbankaccount.BankNameValidator = merchantuserbankaccountDescBankName.Validators[0].(func(int32) error)
	// merchantuserbankaccountDescAccountNumber is the schema descriptor for account_number field.
	merchantuserbankaccountDescAccountNumber := merchantuserbankaccountFields[6].Descriptor()
	// merchantuserbankaccount.AccountNumberValidator is a validator for the "account_number" field. It is called by the builders before save.
	merchantuserbankaccount.AccountNumberValidator = merchantuserbankaccountDescAccountNumber.Validators[0].(func(string) error)
	// merchantuserbankaccountDescAccountName is the schema descriptor for account_name field.
	merchantuserbankaccountDescAccountName := merchantuserbankaccountFields[7].Descriptor()
	// merchantuserbankaccount.AccountNameValidator is a validator for the "account_name" field. It is called by the builders before save.
	merchantuserbankaccount.AccountNameValidator = merchantuserbankaccountDescAccountName.Validators[0].(func(string) error)
	paymentFields := schema.Payment{}.Fields()
	_ = paymentFields
	// paymentDescCreatedBy is the schema descriptor for created_by field.
	paymentDescCreatedBy := paymentFields[1].Descriptor()
	// payment.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	payment.CreatedByValidator = paymentDescCreatedBy.Validators[0].(func(string) error)
	// paymentDescCreatedAt is the schema descriptor for created_at field.
	paymentDescCreatedAt := paymentFields[2].Descriptor()
	// payment.DefaultCreatedAt holds the default value on creation for the created_at field.
	payment.DefaultCreatedAt = paymentDescCreatedAt.Default.(func() time.Time)
	// paymentDescUpdatedBy is the schema descriptor for updated_by field.
	paymentDescUpdatedBy := paymentFields[3].Descriptor()
	// payment.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	payment.UpdatedByValidator = paymentDescUpdatedBy.Validators[0].(func(string) error)
	// paymentDescUpdatedAt is the schema descriptor for updated_at field.
	paymentDescUpdatedAt := paymentFields[4].Descriptor()
	// payment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	payment.DefaultUpdatedAt = paymentDescUpdatedAt.Default.(func() time.Time)
	// payment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	payment.UpdateDefaultUpdatedAt = paymentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymentDescMerchantID is the schema descriptor for merchant_id field.
	paymentDescMerchantID := paymentFields[7].Descriptor()
	// payment.DefaultMerchantID holds the default value on creation for the merchant_id field.
	payment.DefaultMerchantID = paymentDescMerchantID.Default.(int64)
	// payment.MerchantIDValidator is a validator for the "merchant_id" field. It is called by the builders before save.
	payment.MerchantIDValidator = paymentDescMerchantID.Validators[0].(func(int64) error)
	// paymentDescMerchantUserID is the schema descriptor for merchant_user_id field.
	paymentDescMerchantUserID := paymentFields[8].Descriptor()
	// payment.DefaultMerchantUserID holds the default value on creation for the merchant_user_id field.
	payment.DefaultMerchantUserID = paymentDescMerchantUserID.Default.(int64)
	// payment.MerchantUserIDValidator is a validator for the "merchant_user_id" field. It is called by the builders before save.
	payment.MerchantUserIDValidator = paymentDescMerchantUserID.Validators[0].(func(int64) error)
	// paymentDescMethod is the schema descriptor for method field.
	paymentDescMethod := paymentFields[9].Descriptor()
	// payment.DefaultMethod holds the default value on creation for the method field.
	payment.DefaultMethod = paymentDescMethod.Default.(int32)
	// payment.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	payment.MethodValidator = paymentDescMethod.Validators[0].(func(int32) error)
	// paymentDescType is the schema descriptor for type field.
	paymentDescType := paymentFields[10].Descriptor()
	// payment.DefaultType holds the default value on creation for the type field.
	payment.DefaultType = paymentDescType.Default.(int32)
	// payment.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	payment.TypeValidator = paymentDescType.Validators[0].(func(int32) error)
	// paymentDescStatus is the schema descriptor for status field.
	paymentDescStatus := paymentFields[11].Descriptor()
	// payment.DefaultStatus holds the default value on creation for the status field.
	payment.DefaultStatus = paymentDescStatus.Default.(int32)
	// payment.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	payment.StatusValidator = paymentDescStatus.Validators[0].(func(int32) error)
	paymentbankingdetailFields := schema.PaymentBankingDetail{}.Fields()
	_ = paymentbankingdetailFields
	// paymentbankingdetailDescCreatedAt is the schema descriptor for created_at field.
	paymentbankingdetailDescCreatedAt := paymentbankingdetailFields[1].Descriptor()
	// paymentbankingdetail.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymentbankingdetail.DefaultCreatedAt = paymentbankingdetailDescCreatedAt.Default.(func() time.Time)
	// paymentbankingdetailDescUpdatedAt is the schema descriptor for updated_at field.
	paymentbankingdetailDescUpdatedAt := paymentbankingdetailFields[2].Descriptor()
	// paymentbankingdetail.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymentbankingdetail.DefaultUpdatedAt = paymentbankingdetailDescUpdatedAt.Default.(func() time.Time)
	// paymentbankingdetail.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymentbankingdetail.UpdateDefaultUpdatedAt = paymentbankingdetailDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymentbankingdetailDescCreatedBy is the schema descriptor for created_by field.
	paymentbankingdetailDescCreatedBy := paymentbankingdetailFields[3].Descriptor()
	// paymentbankingdetail.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	paymentbankingdetail.CreatedByValidator = paymentbankingdetailDescCreatedBy.Validators[0].(func(string) error)
	// paymentbankingdetailDescUpdatedBy is the schema descriptor for updated_by field.
	paymentbankingdetailDescUpdatedBy := paymentbankingdetailFields[4].Descriptor()
	// paymentbankingdetail.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	paymentbankingdetail.UpdatedByValidator = paymentbankingdetailDescUpdatedBy.Validators[0].(func(string) error)
	// paymentbankingdetailDescMerchantUserBankName is the schema descriptor for merchant_user_bank_name field.
	paymentbankingdetailDescMerchantUserBankName := paymentbankingdetailFields[7].Descriptor()
	// paymentbankingdetail.MerchantUserBankNameValidator is a validator for the "merchant_user_bank_name" field. It is called by the builders before save.
	paymentbankingdetail.MerchantUserBankNameValidator = paymentbankingdetailDescMerchantUserBankName.Validators[0].(func(int32) error)
	// paymentbankingdetailDescSystemAccountBankName is the schema descriptor for system_account_bank_name field.
	paymentbankingdetailDescSystemAccountBankName := paymentbankingdetailFields[10].Descriptor()
	// paymentbankingdetail.SystemAccountBankNameValidator is a validator for the "system_account_bank_name" field. It is called by the builders before save.
	paymentbankingdetail.SystemAccountBankNameValidator = paymentbankingdetailDescSystemAccountBankName.Validators[0].(func(int32) error)
	paymentcryptodetailFields := schema.PaymentCryptoDetail{}.Fields()
	_ = paymentcryptodetailFields
	// paymentcryptodetailDescCreatedAt is the schema descriptor for created_at field.
	paymentcryptodetailDescCreatedAt := paymentcryptodetailFields[1].Descriptor()
	// paymentcryptodetail.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymentcryptodetail.DefaultCreatedAt = paymentcryptodetailDescCreatedAt.Default.(func() time.Time)
	// paymentcryptodetailDescUpdatedAt is the schema descriptor for updated_at field.
	paymentcryptodetailDescUpdatedAt := paymentcryptodetailFields[2].Descriptor()
	// paymentcryptodetail.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymentcryptodetail.DefaultUpdatedAt = paymentcryptodetailDescUpdatedAt.Default.(func() time.Time)
	// paymentcryptodetail.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymentcryptodetail.UpdateDefaultUpdatedAt = paymentcryptodetailDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymentcryptodetailDescCreatedBy is the schema descriptor for created_by field.
	paymentcryptodetailDescCreatedBy := paymentcryptodetailFields[3].Descriptor()
	// paymentcryptodetail.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	paymentcryptodetail.CreatedByValidator = paymentcryptodetailDescCreatedBy.Validators[0].(func(string) error)
	// paymentcryptodetailDescUpdatedBy is the schema descriptor for updated_by field.
	paymentcryptodetailDescUpdatedBy := paymentcryptodetailFields[4].Descriptor()
	// paymentcryptodetail.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	paymentcryptodetail.UpdatedByValidator = paymentcryptodetailDescUpdatedBy.Validators[0].(func(string) error)
	// paymentcryptodetailDescCryptoType is the schema descriptor for crypto_type field.
	paymentcryptodetailDescCryptoType := paymentcryptodetailFields[5].Descriptor()
	// paymentcryptodetail.DefaultCryptoType holds the default value on creation for the crypto_type field.
	paymentcryptodetail.DefaultCryptoType = paymentcryptodetailDescCryptoType.Default.(int32)
	// paymentcryptodetail.CryptoTypeValidator is a validator for the "crypto_type" field. It is called by the builders before save.
	paymentcryptodetail.CryptoTypeValidator = paymentcryptodetailDescCryptoType.Validators[0].(func(int32) error)
	// paymentcryptodetailDescCryptoNetworkType is the schema descriptor for crypto_network_type field.
	paymentcryptodetailDescCryptoNetworkType := paymentcryptodetailFields[6].Descriptor()
	// paymentcryptodetail.DefaultCryptoNetworkType holds the default value on creation for the crypto_network_type field.
	paymentcryptodetail.DefaultCryptoNetworkType = paymentcryptodetailDescCryptoNetworkType.Default.(int32)
	// paymentcryptodetail.CryptoNetworkTypeValidator is a validator for the "crypto_network_type" field. It is called by the builders before save.
	paymentcryptodetail.CryptoNetworkTypeValidator = paymentcryptodetailDescCryptoNetworkType.Validators[0].(func(int32) error)
	// paymentcryptodetailDescCryptoWalletName is the schema descriptor for crypto_wallet_name field.
	paymentcryptodetailDescCryptoWalletName := paymentcryptodetailFields[7].Descriptor()
	// paymentcryptodetail.DefaultCryptoWalletName holds the default value on creation for the crypto_wallet_name field.
	paymentcryptodetail.DefaultCryptoWalletName = paymentcryptodetailDescCryptoWalletName.Default.(int32)
	// paymentcryptodetail.CryptoWalletNameValidator is a validator for the "crypto_wallet_name" field. It is called by the builders before save.
	paymentcryptodetail.CryptoWalletNameValidator = paymentcryptodetailDescCryptoWalletName.Validators[0].(func(int32) error)
	// paymentcryptodetailDescReceiverAddress is the schema descriptor for receiver_address field.
	paymentcryptodetailDescReceiverAddress := paymentcryptodetailFields[8].Descriptor()
	// paymentcryptodetail.ReceiverAddressValidator is a validator for the "receiver_address" field. It is called by the builders before save.
	paymentcryptodetail.ReceiverAddressValidator = paymentcryptodetailDescReceiverAddress.Validators[0].(func(string) error)
	paymentewalletdetailFields := schema.PaymentEWalletDetail{}.Fields()
	_ = paymentewalletdetailFields
	// paymentewalletdetailDescCreatedAt is the schema descriptor for created_at field.
	paymentewalletdetailDescCreatedAt := paymentewalletdetailFields[1].Descriptor()
	// paymentewalletdetail.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymentewalletdetail.DefaultCreatedAt = paymentewalletdetailDescCreatedAt.Default.(func() time.Time)
	// paymentewalletdetailDescUpdatedAt is the schema descriptor for updated_at field.
	paymentewalletdetailDescUpdatedAt := paymentewalletdetailFields[2].Descriptor()
	// paymentewalletdetail.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymentewalletdetail.DefaultUpdatedAt = paymentewalletdetailDescUpdatedAt.Default.(func() time.Time)
	// paymentewalletdetail.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymentewalletdetail.UpdateDefaultUpdatedAt = paymentewalletdetailDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymentewalletdetailDescCreatedBy is the schema descriptor for created_by field.
	paymentewalletdetailDescCreatedBy := paymentewalletdetailFields[3].Descriptor()
	// paymentewalletdetail.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	paymentewalletdetail.CreatedByValidator = paymentewalletdetailDescCreatedBy.Validators[0].(func(string) error)
	// paymentewalletdetailDescUpdatedBy is the schema descriptor for updated_by field.
	paymentewalletdetailDescUpdatedBy := paymentewalletdetailFields[4].Descriptor()
	// paymentewalletdetail.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	paymentewalletdetail.UpdatedByValidator = paymentewalletdetailDescUpdatedBy.Validators[0].(func(string) error)
	// paymentewalletdetailDescEWalletName is the schema descriptor for e_wallet_name field.
	paymentewalletdetailDescEWalletName := paymentewalletdetailFields[7].Descriptor()
	// paymentewalletdetail.EWalletNameValidator is a validator for the "e_wallet_name" field. It is called by the builders before save.
	paymentewalletdetail.EWalletNameValidator = paymentewalletdetailDescEWalletName.Validators[0].(func(int32) error)
	paymenttelcodetailFields := schema.PaymentTelcoDetail{}.Fields()
	_ = paymenttelcodetailFields
	// paymenttelcodetailDescCreatedAt is the schema descriptor for created_at field.
	paymenttelcodetailDescCreatedAt := paymenttelcodetailFields[1].Descriptor()
	// paymenttelcodetail.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymenttelcodetail.DefaultCreatedAt = paymenttelcodetailDescCreatedAt.Default.(func() time.Time)
	// paymenttelcodetailDescUpdatedAt is the schema descriptor for updated_at field.
	paymenttelcodetailDescUpdatedAt := paymenttelcodetailFields[2].Descriptor()
	// paymenttelcodetail.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymenttelcodetail.DefaultUpdatedAt = paymenttelcodetailDescUpdatedAt.Default.(func() time.Time)
	// paymenttelcodetail.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymenttelcodetail.UpdateDefaultUpdatedAt = paymenttelcodetailDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymenttelcodetailDescCreatedBy is the schema descriptor for created_by field.
	paymenttelcodetailDescCreatedBy := paymenttelcodetailFields[3].Descriptor()
	// paymenttelcodetail.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	paymenttelcodetail.CreatedByValidator = paymenttelcodetailDescCreatedBy.Validators[0].(func(string) error)
	// paymenttelcodetailDescUpdatedBy is the schema descriptor for updated_by field.
	paymenttelcodetailDescUpdatedBy := paymenttelcodetailFields[4].Descriptor()
	// paymenttelcodetail.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	paymenttelcodetail.UpdatedByValidator = paymenttelcodetailDescUpdatedBy.Validators[0].(func(string) error)
	// paymenttelcodetailDescTelcoName is the schema descriptor for telco_name field.
	paymenttelcodetailDescTelcoName := paymenttelcodetailFields[5].Descriptor()
	// paymenttelcodetail.DefaultTelcoName holds the default value on creation for the telco_name field.
	paymenttelcodetail.DefaultTelcoName = paymenttelcodetailDescTelcoName.Default.(int32)
	// paymenttelcodetail.TelcoNameValidator is a validator for the "telco_name" field. It is called by the builders before save.
	paymenttelcodetail.TelcoNameValidator = paymenttelcodetailDescTelcoName.Validators[0].(func(int32) error)
	// paymenttelcodetailDescSerialNumber is the schema descriptor for serial_number field.
	paymenttelcodetailDescSerialNumber := paymenttelcodetailFields[6].Descriptor()
	// paymenttelcodetail.DefaultSerialNumber holds the default value on creation for the serial_number field.
	paymenttelcodetail.DefaultSerialNumber = paymenttelcodetailDescSerialNumber.Default.(string)
	// paymenttelcodetailDescCardID is the schema descriptor for card_id field.
	paymenttelcodetailDescCardID := paymenttelcodetailFields[7].Descriptor()
	// paymenttelcodetail.DefaultCardID holds the default value on creation for the card_id field.
	paymenttelcodetail.DefaultCardID = paymenttelcodetailDescCardID.Default.(string)
	// paymenttelcodetailDescChargedAmount is the schema descriptor for charged_amount field.
	paymenttelcodetailDescChargedAmount := paymenttelcodetailFields[8].Descriptor()
	// paymenttelcodetail.DefaultChargedAmount holds the default value on creation for the charged_amount field.
	paymenttelcodetail.DefaultChargedAmount = paymenttelcodetailDescChargedAmount.Default.(uint64)
	// paymenttelcodetailDescAmount is the schema descriptor for amount field.
	paymenttelcodetailDescAmount := paymenttelcodetailFields[9].Descriptor()
	// paymenttelcodetail.DefaultAmount holds the default value on creation for the amount field.
	paymenttelcodetail.DefaultAmount = paymenttelcodetailDescAmount.Default.(uint64)
	revisionFields := schema.Revision{}.Fields()
	_ = revisionFields
	// revisionDescCreatedAt is the schema descriptor for created_at field.
	revisionDescCreatedAt := revisionFields[1].Descriptor()
	// revision.DefaultCreatedAt holds the default value on creation for the created_at field.
	revision.DefaultCreatedAt = revisionDescCreatedAt.Default.(func() time.Time)
	// revisionDescUpdatedAt is the schema descriptor for updated_at field.
	revisionDescUpdatedAt := revisionFields[2].Descriptor()
	// revision.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	revision.DefaultUpdatedAt = revisionDescUpdatedAt.Default.(func() time.Time)
	// revision.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	revision.UpdateDefaultUpdatedAt = revisionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// revisionDescCreatedBy is the schema descriptor for created_by field.
	revisionDescCreatedBy := revisionFields[3].Descriptor()
	// revision.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	revision.CreatedByValidator = revisionDescCreatedBy.Validators[0].(func(string) error)
	// revisionDescUpdatedBy is the schema descriptor for updated_by field.
	revisionDescUpdatedBy := revisionFields[4].Descriptor()
	// revision.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	revision.UpdatedByValidator = revisionDescUpdatedBy.Validators[0].(func(string) error)
	// revisionDescStatus is the schema descriptor for status field.
	revisionDescStatus := revisionFields[5].Descriptor()
	// revision.DefaultStatus holds the default value on creation for the status field.
	revision.DefaultStatus = revisionDescStatus.Default.(int32)
	// revision.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	revision.StatusValidator = revisionDescStatus.Validators[0].(func(int32) error)
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescName is the schema descriptor for name field.
	settingDescName := settingFields[1].Descriptor()
	// setting.NameValidator is a validator for the "name" field. It is called by the builders before save.
	setting.NameValidator = settingDescName.Validators[0].(func(string) error)
	// settingDescType is the schema descriptor for type field.
	settingDescType := settingFields[2].Descriptor()
	// setting.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	setting.TypeValidator = settingDescType.Validators[0].(func(string) error)
	// settingDescValue is the schema descriptor for value field.
	settingDescValue := settingFields[3].Descriptor()
	// setting.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	setting.ValueValidator = settingDescValue.Validators[0].(func(string) error)
	systembankaccountFields := schema.SystemBankAccount{}.Fields()
	_ = systembankaccountFields
	// systembankaccountDescCreatedAt is the schema descriptor for created_at field.
	systembankaccountDescCreatedAt := systembankaccountFields[1].Descriptor()
	// systembankaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	systembankaccount.DefaultCreatedAt = systembankaccountDescCreatedAt.Default.(func() time.Time)
	// systembankaccountDescUpdatedAt is the schema descriptor for updated_at field.
	systembankaccountDescUpdatedAt := systembankaccountFields[2].Descriptor()
	// systembankaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systembankaccount.DefaultUpdatedAt = systembankaccountDescUpdatedAt.Default.(func() time.Time)
	// systembankaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	systembankaccount.UpdateDefaultUpdatedAt = systembankaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// systembankaccountDescCreatedBy is the schema descriptor for created_by field.
	systembankaccountDescCreatedBy := systembankaccountFields[3].Descriptor()
	// systembankaccount.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	systembankaccount.CreatedByValidator = systembankaccountDescCreatedBy.Validators[0].(func(string) error)
	// systembankaccountDescUpdatedBy is the schema descriptor for updated_by field.
	systembankaccountDescUpdatedBy := systembankaccountFields[4].Descriptor()
	// systembankaccount.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	systembankaccount.UpdatedByValidator = systembankaccountDescUpdatedBy.Validators[0].(func(string) error)
	// systembankaccountDescMerchantID is the schema descriptor for merchant_id field.
	systembankaccountDescMerchantID := systembankaccountFields[5].Descriptor()
	// systembankaccount.DefaultMerchantID holds the default value on creation for the merchant_id field.
	systembankaccount.DefaultMerchantID = systembankaccountDescMerchantID.Default.(int64)
	// systembankaccount.MerchantIDValidator is a validator for the "merchant_id" field. It is called by the builders before save.
	systembankaccount.MerchantIDValidator = systembankaccountDescMerchantID.Validators[0].(func(int64) error)
	// systembankaccountDescStatus is the schema descriptor for status field.
	systembankaccountDescStatus := systembankaccountFields[6].Descriptor()
	// systembankaccount.DefaultStatus holds the default value on creation for the status field.
	systembankaccount.DefaultStatus = systembankaccountDescStatus.Default.(int32)
	// systembankaccount.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	systembankaccount.StatusValidator = systembankaccountDescStatus.Validators[0].(func(int32) error)
	// systembankaccountDescBankName is the schema descriptor for bank_name field.
	systembankaccountDescBankName := systembankaccountFields[7].Descriptor()
	// systembankaccount.DefaultBankName holds the default value on creation for the bank_name field.
	systembankaccount.DefaultBankName = systembankaccountDescBankName.Default.(int32)
	// systembankaccount.BankNameValidator is a validator for the "bank_name" field. It is called by the builders before save.
	systembankaccount.BankNameValidator = systembankaccountDescBankName.Validators[0].(func(int32) error)
	// systembankaccountDescAccountNumber is the schema descriptor for account_number field.
	systembankaccountDescAccountNumber := systembankaccountFields[8].Descriptor()
	// systembankaccount.AccountNumberValidator is a validator for the "account_number" field. It is called by the builders before save.
	systembankaccount.AccountNumberValidator = systembankaccountDescAccountNumber.Validators[0].(func(string) error)
	// systembankaccountDescAccountName is the schema descriptor for account_name field.
	systembankaccountDescAccountName := systembankaccountFields[9].Descriptor()
	// systembankaccount.AccountNameValidator is a validator for the "account_name" field. It is called by the builders before save.
	systembankaccount.AccountNameValidator = systembankaccountDescAccountName.Validators[0].(func(string) error)
	// systembankaccountDescBalance is the schema descriptor for balance field.
	systembankaccountDescBalance := systembankaccountFields[11].Descriptor()
	// systembankaccount.DefaultBalance holds the default value on creation for the balance field.
	systembankaccount.DefaultBalance = systembankaccountDescBalance.Default.(uint64)
	// systembankaccountDescDailyBalanceLimit is the schema descriptor for daily_balance_limit field.
	systembankaccountDescDailyBalanceLimit := systembankaccountFields[13].Descriptor()
	// systembankaccount.DefaultDailyBalanceLimit holds the default value on creation for the daily_balance_limit field.
	systembankaccount.DefaultDailyBalanceLimit = systembankaccountDescDailyBalanceLimit.Default.(uint64)
	// systembankaccountDescDailyUsedAmount is the schema descriptor for daily_used_amount field.
	systembankaccountDescDailyUsedAmount := systembankaccountFields[14].Descriptor()
	// systembankaccount.DefaultDailyUsedAmount holds the default value on creation for the daily_used_amount field.
	systembankaccount.DefaultDailyUsedAmount = systembankaccountDescDailyUsedAmount.Default.(int64)
	// systembankaccountDescDailyBalance is the schema descriptor for daily_balance field.
	systembankaccountDescDailyBalance := systembankaccountFields[15].Descriptor()
	// systembankaccount.DefaultDailyBalance holds the default value on creation for the daily_balance field.
	systembankaccount.DefaultDailyBalance = systembankaccountDescDailyBalance.Default.(uint64)
	systemcryptohotwalletFields := schema.SystemCryptoHotWallet{}.Fields()
	_ = systemcryptohotwalletFields
	// systemcryptohotwalletDescCreatedAt is the schema descriptor for created_at field.
	systemcryptohotwalletDescCreatedAt := systemcryptohotwalletFields[1].Descriptor()
	// systemcryptohotwallet.DefaultCreatedAt holds the default value on creation for the created_at field.
	systemcryptohotwallet.DefaultCreatedAt = systemcryptohotwalletDescCreatedAt.Default.(func() time.Time)
	// systemcryptohotwalletDescUpdatedAt is the schema descriptor for updated_at field.
	systemcryptohotwalletDescUpdatedAt := systemcryptohotwalletFields[2].Descriptor()
	// systemcryptohotwallet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systemcryptohotwallet.DefaultUpdatedAt = systemcryptohotwalletDescUpdatedAt.Default.(func() time.Time)
	// systemcryptohotwallet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	systemcryptohotwallet.UpdateDefaultUpdatedAt = systemcryptohotwalletDescUpdatedAt.UpdateDefault.(func() time.Time)
	// systemcryptohotwalletDescCreatedBy is the schema descriptor for created_by field.
	systemcryptohotwalletDescCreatedBy := systemcryptohotwalletFields[3].Descriptor()
	// systemcryptohotwallet.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	systemcryptohotwallet.CreatedByValidator = systemcryptohotwalletDescCreatedBy.Validators[0].(func(string) error)
	// systemcryptohotwalletDescUpdatedBy is the schema descriptor for updated_by field.
	systemcryptohotwalletDescUpdatedBy := systemcryptohotwalletFields[4].Descriptor()
	// systemcryptohotwallet.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	systemcryptohotwallet.UpdatedByValidator = systemcryptohotwalletDescUpdatedBy.Validators[0].(func(string) error)
	// systemcryptohotwalletDescMerchantID is the schema descriptor for merchant_id field.
	systemcryptohotwalletDescMerchantID := systemcryptohotwalletFields[5].Descriptor()
	// systemcryptohotwallet.DefaultMerchantID holds the default value on creation for the merchant_id field.
	systemcryptohotwallet.DefaultMerchantID = systemcryptohotwalletDescMerchantID.Default.(int64)
	// systemcryptohotwallet.MerchantIDValidator is a validator for the "merchant_id" field. It is called by the builders before save.
	systemcryptohotwallet.MerchantIDValidator = systemcryptohotwalletDescMerchantID.Validators[0].(func(int64) error)
	// systemcryptohotwalletDescCryptoType is the schema descriptor for crypto_type field.
	systemcryptohotwalletDescCryptoType := systemcryptohotwalletFields[6].Descriptor()
	// systemcryptohotwallet.DefaultCryptoType holds the default value on creation for the crypto_type field.
	systemcryptohotwallet.DefaultCryptoType = systemcryptohotwalletDescCryptoType.Default.(int32)
	// systemcryptohotwallet.CryptoTypeValidator is a validator for the "crypto_type" field. It is called by the builders before save.
	systemcryptohotwallet.CryptoTypeValidator = systemcryptohotwalletDescCryptoType.Validators[0].(func(int32) error)
	// systemcryptohotwalletDescCryptoNetworkType is the schema descriptor for crypto_network_type field.
	systemcryptohotwalletDescCryptoNetworkType := systemcryptohotwalletFields[7].Descriptor()
	// systemcryptohotwallet.DefaultCryptoNetworkType holds the default value on creation for the crypto_network_type field.
	systemcryptohotwallet.DefaultCryptoNetworkType = systemcryptohotwalletDescCryptoNetworkType.Default.(int32)
	// systemcryptohotwallet.CryptoNetworkTypeValidator is a validator for the "crypto_network_type" field. It is called by the builders before save.
	systemcryptohotwallet.CryptoNetworkTypeValidator = systemcryptohotwalletDescCryptoNetworkType.Validators[0].(func(int32) error)
	// systemcryptohotwalletDescAddress is the schema descriptor for address field.
	systemcryptohotwalletDescAddress := systemcryptohotwalletFields[8].Descriptor()
	// systemcryptohotwallet.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	systemcryptohotwallet.AddressValidator = systemcryptohotwalletDescAddress.Validators[0].(func(string) error)
	// systemcryptohotwalletDescTotalBalance is the schema descriptor for total_balance field.
	systemcryptohotwalletDescTotalBalance := systemcryptohotwalletFields[9].Descriptor()
	// systemcryptohotwallet.DefaultTotalBalance holds the default value on creation for the total_balance field.
	systemcryptohotwallet.DefaultTotalBalance = systemcryptohotwalletDescTotalBalance.Default.(float64)
	// systemcryptohotwalletDescBalance is the schema descriptor for balance field.
	systemcryptohotwalletDescBalance := systemcryptohotwalletFields[10].Descriptor()
	// systemcryptohotwallet.DefaultBalance holds the default value on creation for the balance field.
	systemcryptohotwallet.DefaultBalance = systemcryptohotwalletDescBalance.Default.(float64)
	// systemcryptohotwalletDescStatus is the schema descriptor for status field.
	systemcryptohotwalletDescStatus := systemcryptohotwalletFields[11].Descriptor()
	// systemcryptohotwallet.DefaultStatus holds the default value on creation for the status field.
	systemcryptohotwallet.DefaultStatus = systemcryptohotwalletDescStatus.Default.(int32)
	// systemcryptohotwallet.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	systemcryptohotwallet.StatusValidator = systemcryptohotwalletDescStatus.Validators[0].(func(int32) error)
	systemewalletFields := schema.SystemEWallet{}.Fields()
	_ = systemewalletFields
	// systemewalletDescCreatedAt is the schema descriptor for created_at field.
	systemewalletDescCreatedAt := systemewalletFields[1].Descriptor()
	// systemewallet.DefaultCreatedAt holds the default value on creation for the created_at field.
	systemewallet.DefaultCreatedAt = systemewalletDescCreatedAt.Default.(func() time.Time)
	// systemewalletDescUpdatedAt is the schema descriptor for updated_at field.
	systemewalletDescUpdatedAt := systemewalletFields[2].Descriptor()
	// systemewallet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systemewallet.DefaultUpdatedAt = systemewalletDescUpdatedAt.Default.(func() time.Time)
	// systemewallet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	systemewallet.UpdateDefaultUpdatedAt = systemewalletDescUpdatedAt.UpdateDefault.(func() time.Time)
	// systemewalletDescCreatedBy is the schema descriptor for created_by field.
	systemewalletDescCreatedBy := systemewalletFields[3].Descriptor()
	// systemewallet.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	systemewallet.CreatedByValidator = systemewalletDescCreatedBy.Validators[0].(func(string) error)
	// systemewalletDescUpdatedBy is the schema descriptor for updated_by field.
	systemewalletDescUpdatedBy := systemewalletFields[4].Descriptor()
	// systemewallet.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	systemewallet.UpdatedByValidator = systemewalletDescUpdatedBy.Validators[0].(func(string) error)
	// systemewalletDescEWalletName is the schema descriptor for e_wallet_name field.
	systemewalletDescEWalletName := systemewalletFields[5].Descriptor()
	// systemewallet.DefaultEWalletName holds the default value on creation for the e_wallet_name field.
	systemewallet.DefaultEWalletName = systemewalletDescEWalletName.Default.(int32)
	// systemewallet.EWalletNameValidator is a validator for the "e_wallet_name" field. It is called by the builders before save.
	systemewallet.EWalletNameValidator = systemewalletDescEWalletName.Validators[0].(func(int32) error)
	// systemewalletDescStatus is the schema descriptor for status field.
	systemewalletDescStatus := systemewalletFields[6].Descriptor()
	// systemewallet.DefaultStatus holds the default value on creation for the status field.
	systemewallet.DefaultStatus = systemewalletDescStatus.Default.(int32)
	// systemewallet.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	systemewallet.StatusValidator = systemewalletDescStatus.Validators[0].(func(int32) error)
	// systemewalletDescMerchantID is the schema descriptor for merchant_id field.
	systemewalletDescMerchantID := systemewalletFields[7].Descriptor()
	// systemewallet.DefaultMerchantID holds the default value on creation for the merchant_id field.
	systemewallet.DefaultMerchantID = systemewalletDescMerchantID.Default.(int64)
	// systemewallet.MerchantIDValidator is a validator for the "merchant_id" field. It is called by the builders before save.
	systemewallet.MerchantIDValidator = systemewalletDescMerchantID.Validators[0].(func(int64) error)
	// systemewalletDescAccountPhoneNumber is the schema descriptor for account_phone_number field.
	systemewalletDescAccountPhoneNumber := systemewalletFields[8].Descriptor()
	// systemewallet.AccountPhoneNumberValidator is a validator for the "account_phone_number" field. It is called by the builders before save.
	systemewallet.AccountPhoneNumberValidator = systemewalletDescAccountPhoneNumber.Validators[0].(func(string) error)
	// systemewalletDescAccountName is the schema descriptor for account_name field.
	systemewalletDescAccountName := systemewalletFields[9].Descriptor()
	// systemewallet.AccountNameValidator is a validator for the "account_name" field. It is called by the builders before save.
	systemewallet.AccountNameValidator = systemewalletDescAccountName.Validators[0].(func(string) error)
	// systemewalletDescBalance is the schema descriptor for balance field.
	systemewalletDescBalance := systemewalletFields[10].Descriptor()
	// systemewallet.DefaultBalance holds the default value on creation for the balance field.
	systemewallet.DefaultBalance = systemewalletDescBalance.Default.(uint64)
	// systemewalletDescDailyBalance is the schema descriptor for daily_balance field.
	systemewalletDescDailyBalance := systemewalletFields[11].Descriptor()
	// systemewallet.DefaultDailyBalance holds the default value on creation for the daily_balance field.
	systemewallet.DefaultDailyBalance = systemewalletDescDailyBalance.Default.(uint64)
	// systemewalletDescDailyBalanceLimit is the schema descriptor for daily_balance_limit field.
	systemewalletDescDailyBalanceLimit := systemewalletFields[12].Descriptor()
	// systemewallet.DefaultDailyBalanceLimit holds the default value on creation for the daily_balance_limit field.
	systemewallet.DefaultDailyBalanceLimit = systemewalletDescDailyBalanceLimit.Default.(uint64)
	// systemewalletDescDailyUsedAmount is the schema descriptor for daily_used_amount field.
	systemewalletDescDailyUsedAmount := systemewalletFields[13].Descriptor()
	// systemewallet.DefaultDailyUsedAmount holds the default value on creation for the daily_used_amount field.
	systemewallet.DefaultDailyUsedAmount = systemewalletDescDailyUsedAmount.Default.(int64)
}
