// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"gitlab.com/mcuc/monorepo/backend/stark/pkg/ent/systemcryptohotwallet"
)

// SystemCryptoHotWallet is the model entity for the SystemCryptoHotWallet schema.
type SystemCryptoHotWallet struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// MerchantID holds the value of the "merchant_id" field.
	MerchantID int64 `json:"merchant_id,omitempty"`
	// CryptoType holds the value of the "crypto_type" field.
	CryptoType int32 `json:"crypto_type,omitempty"`
	// CryptoNetworkType holds the value of the "crypto_network_type" field.
	CryptoNetworkType int32 `json:"crypto_network_type,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// TotalBalance holds the value of the "total_balance" field.
	TotalBalance float64 `json:"total_balance,omitempty"`
	// Balance holds the value of the "balance" field.
	Balance float64 `json:"balance,omitempty"`
	// Status holds the value of the "status" field.
	Status int32 `json:"status,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SystemCryptoHotWallet) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case systemcryptohotwallet.FieldTotalBalance, systemcryptohotwallet.FieldBalance:
			values[i] = new(sql.NullFloat64)
		case systemcryptohotwallet.FieldID, systemcryptohotwallet.FieldMerchantID, systemcryptohotwallet.FieldCryptoType, systemcryptohotwallet.FieldCryptoNetworkType, systemcryptohotwallet.FieldStatus:
			values[i] = new(sql.NullInt64)
		case systemcryptohotwallet.FieldCreatedBy, systemcryptohotwallet.FieldUpdatedBy, systemcryptohotwallet.FieldAddress:
			values[i] = new(sql.NullString)
		case systemcryptohotwallet.FieldCreatedAt, systemcryptohotwallet.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type SystemCryptoHotWallet", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SystemCryptoHotWallet fields.
func (schw *SystemCryptoHotWallet) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case systemcryptohotwallet.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			schw.ID = int64(value.Int64)
		case systemcryptohotwallet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				schw.CreatedAt = value.Time
			}
		case systemcryptohotwallet.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				schw.UpdatedAt = value.Time
			}
		case systemcryptohotwallet.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				schw.CreatedBy = value.String
			}
		case systemcryptohotwallet.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				schw.UpdatedBy = value.String
			}
		case systemcryptohotwallet.FieldMerchantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field merchant_id", values[i])
			} else if value.Valid {
				schw.MerchantID = value.Int64
			}
		case systemcryptohotwallet.FieldCryptoType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field crypto_type", values[i])
			} else if value.Valid {
				schw.CryptoType = int32(value.Int64)
			}
		case systemcryptohotwallet.FieldCryptoNetworkType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field crypto_network_type", values[i])
			} else if value.Valid {
				schw.CryptoNetworkType = int32(value.Int64)
			}
		case systemcryptohotwallet.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				schw.Address = value.String
			}
		case systemcryptohotwallet.FieldTotalBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_balance", values[i])
			} else if value.Valid {
				schw.TotalBalance = value.Float64
			}
		case systemcryptohotwallet.FieldBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				schw.Balance = value.Float64
			}
		case systemcryptohotwallet.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				schw.Status = int32(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this SystemCryptoHotWallet.
// Note that you need to call SystemCryptoHotWallet.Unwrap() before calling this method if this SystemCryptoHotWallet
// was returned from a transaction, and the transaction was committed or rolled back.
func (schw *SystemCryptoHotWallet) Update() *SystemCryptoHotWalletUpdateOne {
	return (&SystemCryptoHotWalletClient{config: schw.config}).UpdateOne(schw)
}

// Unwrap unwraps the SystemCryptoHotWallet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (schw *SystemCryptoHotWallet) Unwrap() *SystemCryptoHotWallet {
	tx, ok := schw.config.driver.(*txDriver)
	if !ok {
		panic("ent: SystemCryptoHotWallet is not a transactional entity")
	}
	schw.config.driver = tx.drv
	return schw
}

// String implements the fmt.Stringer.
func (schw *SystemCryptoHotWallet) String() string {
	var builder strings.Builder
	builder.WriteString("SystemCryptoHotWallet(")
	builder.WriteString(fmt.Sprintf("id=%v", schw.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(schw.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(schw.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", created_by=")
	builder.WriteString(schw.CreatedBy)
	builder.WriteString(", updated_by=")
	builder.WriteString(schw.UpdatedBy)
	builder.WriteString(", merchant_id=")
	builder.WriteString(fmt.Sprintf("%v", schw.MerchantID))
	builder.WriteString(", crypto_type=")
	builder.WriteString(fmt.Sprintf("%v", schw.CryptoType))
	builder.WriteString(", crypto_network_type=")
	builder.WriteString(fmt.Sprintf("%v", schw.CryptoNetworkType))
	builder.WriteString(", address=")
	builder.WriteString(schw.Address)
	builder.WriteString(", total_balance=")
	builder.WriteString(fmt.Sprintf("%v", schw.TotalBalance))
	builder.WriteString(", balance=")
	builder.WriteString(fmt.Sprintf("%v", schw.Balance))
	builder.WriteString(", status=")
	builder.WriteString(fmt.Sprintf("%v", schw.Status))
	builder.WriteByte(')')
	return builder.String()
}

// SystemCryptoHotWallets is a parsable slice of SystemCryptoHotWallet.
type SystemCryptoHotWallets []*SystemCryptoHotWallet

func (schw SystemCryptoHotWallets) config(cfg config) {
	for _i := range schw {
		schw[_i].config = cfg
	}
}
