# Default values for main-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: nginx
  pullPolicy: Always
  secret: ""
  name: "nginx"
  # Overrides the image tag. default is latest.
  tag: "latest"
  command: ["envoy"]
  args: ["-c", "/etc/envoy.yaml"]



# Chart name override
#nameOverride: ""
# Full name override
#fullnameOverride: ""

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limit: maximum resources of pod, when pod use more resources than limit, it will be killed
  limits:
    cpu: 100m
    memory: 128Mi
# request: resources which the pod needs to run comfortably
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  ports:
    - name: "http"
      port: 80
      targetPort: 80

# Additional pod annotations
podAnnotations: {}

# Additional environment variables to set
#env:
#- name: DATABASE_URL
#  valueFrom:
#    secretKeyRef:
#      name: secretName
#      key: database_url
#- name: foo
#  value: bar

vaultsecret:
  enabled: false
# Path to vault secret
#  path: "/kv/apps/example"
# Secret name will be created by vault-operator
#  secretName : "example"

# Network Load Balancer config
loadBalancer:
  enabled: true
  host: "example.com"
  sslCertArn: ""
  #NLB listen port: default 443
  port: 443
  healthCheckPath: /status
  #Service target port, default 8080
  targetPort: 8080
  
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  # Percentage of CPU request
  targetCPUUtilizationPercentage: 80
  # Percentage of Memory request
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
