replicaCount: 1
namespace: default
vaultsecret:
  enabled: true
  secretName: groot
  path: kv/apps/groot
image:
  secret: aloppay
  repository: registry.gitlab.com
  pullPolicy: Always
  name: mcuc/monorepo/groot
  tag: prod
resources: {}
env:
  - name: GROOT_DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: natasha
        key: database_url
service:
  type: ClusterIP
  ports:
    - name: "grpc"
      port: 8080
      targetPort: 8080