replicaCount: 1
namespace: default
vaultsecret:
  enabled: true
  secretName: natasha
  path: kv/apps/natasha
image:
  secret: alopay
  repository: registry.gitlab.com
  pullPolicy: Always
  name: mcuc/monorepo/natasha
  tag: dev
env:
  - name: NATASHA_DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: natasha
        key: database_url
resources: {}
service:
  type: ClusterIP
  ports:
    - name: "grpc"
      port: 8080
      targetPort: 8080