environmentVars:
  - name: VAULT_TOKEN
    valueFrom:
      secretKeyRef:
        name: vault-secrets-operator
        key: VAULT_TOKEN
  - name: VAULT_TOKEN_LEASE_DURATION
    valueFrom:
      secretKeyRef:
        name: vault-secrets-operator
        key: VAULT_TOKEN_LEASE_DURATION

vault:
  # The reconciliationTime value determines after which time the Vault secret is
  # processed again. This can be used to update a the Kubernetes secret, when the
  # Vault secret changes. A value of 0 will disable the automatic update.
  # You can specify all namespaces the operator should watch. Therefore pass a
  # comma separated list via the namespaces value. If the value is empty the operator
  # will watch all namespaces. If the value is empty and rbac.namespaced is set to
  # true, then the namespace of the release will be used.
  reconciliationTime: 300
  address: "http://vault-internal:8200"
