FROM golang:1.16

RUN apt-get update
RUN apt-get install \
    coreutils \
    python3 \
    git \
    openssh-client \
    curl \
    make \
    bash \
    jq \
    upx \
    unzip \
    libprotobuf-dev \
    docker -y

ENV NODE_VERSION=12.19.0
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"

ENV GOPATH /go
ENV PATH /go/bin:$PATH
ENV GO111MODULE on

ENV GRPC_WEB_VERSION=1.2.1
RUN curl -sSL \
  https://github.com/grpc/grpc-web/releases/download/${GRPC_WEB_VERSION}/protoc-gen-grpc-web-${GRPC_WEB_VERSION}-linux-x86_64 \
  -o /usr/local/bin/protoc-gen-grpc-web && \
  chmod +x /usr/local/bin/protoc-gen-grpc-web

ENV PROTOBUF_VERSION=3.12.4
RUN mkdir -p /tmp/protoc && \
  curl -sSL \
  https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip \
  -o /tmp/protoc/protoc.zip && \
  cd /tmp/protoc && \
  unzip protoc.zip && \
  mv /tmp/protoc/include/* /usr/local/include/ && \
  cp /tmp/protoc/bin/protoc /usr/local/bin/protoc && \
  chmod +x /usr/local/bin/protoc

RUN mkdir -p /go/src/github.com/envoyproxy && \
    git clone https://github.com/envoyproxy/protoc-gen-validate /go/src/github.com/envoyproxy/protoc-gen-validate && \
    cd /go/src/github.com/envoyproxy/protoc-gen-validate && \
    git checkout v0.4.1 && \
    go install

RUN upx --lzma /usr/local/bin/*