listener:
  tcp:
    address: 0.0.0.0
    port: 8080
    secure: false

logger:
  pretty: true
  level: DEBUG

database:
  url: ${NATASHA_DATABASE_URL}
  debug: false

hawkeye:
  address: hawkeye
  port: 8080
  secure: false

mex_twt_token_signing:
  # 10 years expired
  expires_time: 315360000
  private_key: "-----BEGIN RSA PRIVATE KEY-----\nMIIJJwIBAAKCAgEAyh0KzceKiOUBoQMovtTmAidJpmrH/YXVlo18kpqlVLcMWl8t\nTBTHcarNmA0gYGQO9ER7yE3Ri9Om6EvMDwnXKjPsIqz1ukqmdi+wW3HrbjAP+PMC\nLo9sVLP9OMRw8tMrrAtfi0rPFMBdnW58B+0pejtw8w5/F0o/tWGkOqOqu+1OrVpO\nCTPQKdC+tpvxxE6ZjoQ0QqJ87qMhy6yMY6t44cevsKssf0JbL0QBAOgm7FiwGFa0\nT2iGS1Y2a2Bng+6BzQCAIBgYkvRZgwMk3l05NY4J/Jnfk7Q93lTP9i/TfRpxv2YV\n+tlFdtBO643nKhgQaM9hofxwAJOwafMJLgvH1qnrGhHbpv2M3aZm0TT+aspteDM9\na68sE+YC2JEgjTCzVDNl2g90RVk1wEpjIIWF9JSvPBn8l0KTVXmvAxv64ogpfIYo\nYjdPd4CoJQIBJI4ezk4oguP8E+EBJL7lC7UV+jFNFoBjYKwKHmTLXPnKtPQ1zB8Q\nsayLHoHt39z1wtEiQRmmBzia76l/GyGrvt2PSThqVLmbQcTpm2aMAhZy3rQ19CJw\nV0XEhKCREyZpbTIW0qZlMAMiEnl8iEXBur8V4A7AzlS2Wa6NODnq2FMuncqL07M6\njZM4CZV4CYCvHLV8HMviQPGe6h1xb5vbl+Lvk4B2LP7pxsgUkgewnVGa8x8CAwEA\nAQKCAgBzuCseZNgxxwSmvptOn7DNnNbzXIIC6uS+nWWsvrRYi7Gb8JCL1f3XW9b4\n7tMRvVg+jRNePQf0CguvRu6f0Z+K/019ERBkSCeE1Ysg4FnOreAHRoOCSwXYfXFH\nVlng/f0sNRrQMtXb6MPwxnhnRWeRH4Vs9GjZ2d4eKLiSBnFTxexdHq49YJgXyPfY\nr/K91c7fpVwSptvm+in4ZmO/EUdV5jH2chs5BbIVntcAQOtAOQsh9EqqiIsTiVoB\nIqJCDIXu7RFuzr0LLrIta9hpJHED875ODX/QHsuph1/Gcd2h7EkiL/33sPyvqVb2\nUToAhOSoTcx1pYYvHmBMWSVxYrdYcVg59yQSmzgs1l8C/gHo8w/T23UVwZXAIyzY\nqGr3X87xJCb8/vq/TmEfeLdmoTGHaO9p+gSOVqiunkfOE6LxCmvNNGNATV/SwHtx\nIIEXI0i5LoSGjqp/KNPnB6b1Dw8kYL/w3BN614wnp4AU0S0MaLM2RsXq4UyzB4ET\nDMTRxQpy/gmrbRlIRpzfyGkLrRCq2NCwSS+gyxnYR6og8Yu46YLUsvmerMP65nzS\nwe51R2A0gN/Oj+70+NRBdXvDPxVZXS/QWBtQ03+yIbDySQgyAlKYrHJc6x56athb\nXBlYDiC47PhDavFItF4XENvU74YSYYT42EvfWbXD5UtAUZ+wkQKCAQEA5QDnQEO8\nwIK01Y+jBNRXb9klJ+6oEa/fIaCo9tb0iF6/tSVVMiEM02f6G99y3cnoTFMJqyGX\n+nbVnaLr7D6Nvc0KyGKo7IkmToS6NV1+gVpmPWhruVb4NbTZEKO/LWsPJJ5p8P26\na0cjhU2A4NwfZeAAieY/SOlA+fZLTZVn3nZoNklCxdj2suRYyIO7WB50xmABXnQ/\nYT9db1ND7XIZir4DLN6SiianNzYdbSPTCAUgIYchUOegUvKZti/ccHDu2OS/iCqq\nKdeRtnQIV6IM9j5P72fAyvmlrf9d9aOPJU+JxrTerTcmbyj4HtcQ4mo57zK412pX\nWCOqQmV70iokCQKCAQEA4fCfiFAYsNNVZaBTP2uLYAg2LSJJcn5GdVTgXVTHoAL6\nCBJ1nBVcAWrc4ZW97fpOSzhPtJId9D/NzMMRLf7te2KYCpqiluRqxzATV6OW9LuI\nutY6m6pzht9T8hyP1WiRCNGRIHfPugZDDOdlAlt3jyuJdZOObZiSJeumnQkwA9eL\nhJK3ZgBsRxFfRS5mJXPxB0PMKaDp4MO28EDLx7I7wy5Ix5HvQvhhi9MKawC90ByE\nxFP5Ze+OYGmQZhEvQAwFIpy22daR1AYxPv4+5VawNY2a6c+Oh9R3san7SbxLjyw4\nGx353kEcUGS6ter6gtSLv+SLL2ZwrMv6Ws6jB8K35wKCAQA8LoOXcPW+xdrOMQRP\ndZpQ64kHOIH0u/pwtO8Sh6UV3YiWC2ybUvIy8KVbA9sFDFW/ESd+UMLG8Mnstm83\n06yeT69gwATSvKxTgDALbDmdtusdgj6lI4TxYEiXReEtB3CgV/1Rduyx2q0sEBUp\ngs/Bjx+1HcxN1fbceeyKRBRa81UpxxEEO6OBmd73Ox9V5hMcOwjBEN3DKcrdQc2d\nLhomSw88kHWEVuok6VTMZNjFx8sM5J1NzMFmaxkYNvXAmv06BMuM9mFnw54oi8/R\nb+XmJLQPH34cGYV/95dywXwR+xgjH09RyCeSmPqz6CMozW/SO8s12V2A7UaGUnM6\n5RY5AoIBABEV/Tp1tChLEv4obaMyIswUUuR+30cFPZbJ4F2ud5omH3pUywgOpXKF\n/kYg6MgCUcFmdMCW/CToXkvJxJbR3GukPRMwNnNquphtjkjmWhgPxns6kBwNe8cL\nRHHerxHYYn9kObFW3iKXLqLfLMhM2nG9PRvjGLY4/3RWqbbeZv8jYa2Y2r2f8pA9\nRBMbOyZB6kw+WEYdoRIaOs9YVxC27cYIzgApjQpndhj40KTe3XvLbE7cetO2lfG8\nieruCcCyKAFCEKHQlB6QiVDWMTNupsyl9L0RsRmce6C31gTxdFVTZrrGPYsNKXL6\n6xOuvVr/b8IHKm9fM84dbsVHMxT3KKkCggEAcIKONfXhoIBcSGwC3FzwOk/KLea7\nV/OHzdgYMAr6JqXKdyGikg516W7ziJBDwGlDkYhuFLbEMzGdSODgVfTQIBHSEG70\nrDREUYHXLsVpcrGbJBDyusvr0AQlR6K4+T1DEH83Ful6b471tSWC15Dle5H0G1NI\nSsYCpd24amv0Y7EZcSZ4MwRXpZAW7fH/lftslxnnK0cuFJfaW12horSbUCxUgg19\n0NFA3YbqDM4OffDyeSLKWs1lYBolkULf7b6M7jnebdHIzpKhUxS1yMBMRM7say4o\nWsX17/UOAfpuzs6dNmMuQEMmQCw9pJlmR9VajM1dkL/6oO2WFycAuTaO5A==\n-----END RSA PRIVATE KEY-----"
  issuer: ALOPAY
  audience: MEX

feature_flag:
  enable_hawkeye: true

merchant_call:
  email:
    subject: Notice of Payment Rejection from AloPay
    template: payment_reject.html