{{ $autoScaling := .Values.autoscaling | default dict}}
{{- if $autoScaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "main-chart.fullname" . }}
  labels:
    {{- include "main-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "main-chart.fullname" . }}
  minReplicas: {{ required "autoscaling.minReplicas is required" $autoScaling.minReplicas }}
  maxReplicas: {{ required "autoscaling.maxReplicas is required" $autoScaling.maxReplicas }}
  metrics:
    {{- if $autoScaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ $autoScaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $autoScaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ $autoScaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
