apiVersion: v1
kind: Service
metadata:
  name: {{ include "main-chart.fullname" . }}
  labels:
    {{- include "main-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $val := .Values.service.ports }}
    - port: {{ $val.port }}
      targetPort: {{ $val.targetPort }}
      {{- if $val.name }}
      name: {{ $val.name }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "main-chart.selectorLabels" . | nindent 4 }}
