{{ $vaultsecret := .Values.vaultsecret | default dict}}
{{- if $vaultsecret.enabled }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ $vaultsecret.secretName }}
spec:
  path: {{ $vaultsecret.path }}
  type: Opaque
{{- end }}
